version: '3'

services:
  db:
    image: postgres:16
    container_name: 'postgres'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: 'python3.11'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.2.4
    container_name: 'redis'

  celery:
    build: .
    container_name: 'celery'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    command: celery -A blog_project worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  pg_data:

