# Generated by Django 5.0.1 on 2024-02-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Successfully published'), ('moderation', 'Submitted for moderation'), ('rejected', 'Publication was rejected')], default='moderation', max_length=20),
        ),
    ]
