# Generated by Django 5.0.1 on 2024-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('published', 'Successfully published'), ('moderation', 'Submitted for moderation')], default='moderation', max_length=20),
        ),
    ]
